apiVersion: v1
kind: Pod
metadata:
  name: s3-access-test
  namespace: default
spec:
  serviceAccountName: s3-access-sa
  containers:
    - name: awscli
      image: amazon/aws-cli
      command: [ "sleep", "3600" ]
